# Generated by Django 4.0.6 on 2022-07-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unit', models.CharField(max_length=10)),
                ('shop', models.CharField(max_length=15)),
                ('complete', models.BooleanField(default=False)),
                ('shoplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoplist')),
            ],
        ),
    ]
